export const SET_THEME = "SET_THEME";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FONT_SIZE = "SET_FONT_SIZE";

export const SET_INPUT = "SET_INPUT";
export const SET_OUTPUT = "SET_OUTPUT";

export const SET_LOADING = "SET_LOADING";
export const RESET_LOADING = "RESET_LOADING";

export const SET_COMPILE_ON = "SET_COMPILE_ON";
export const SET_COMPILE_OFF = "SET_COMPILE_OFF";

export const LEAVE_ROOM = "LEAVE_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";

export const SHOW_GRAPH = "SHOW_GRAPH";
export const HIDE_GRAPH = "HIDE_GRAPH";

export const NOTIFY_OUTPUT_ERROR = "NOTIFY_OUTPUT_ERROR";
export const NOTIFY_OUTPUT_SUCCESS = "NOTIFY_OUTPUT_SUCCESS";

export const CONTEST_ENDED = "CONTEST_ENDED";
export const CONTEST_UPDATED = "CONTEST_UPDATED";
export const UPDATE_MIN_RATING = "UPDATE_MIN_RATING";
export const UPDATE_MAX_RATING = "UPDATE_MAX_RATING";
export const UPDATE_PROBLEM_TAGS = "UPDATE_PROBLEM_TAGS";
export const UPDATE_MAX_DURATION = "UPDATE_MAX_DURATION";

export const SET_QUESTION_LOADING = "SET_QUESTION_LOADING";
export const RESET_QUESTION_LOADING = "RESET_QUESTION_LOADING";

export const SHOW_CONTEST_ENDED_MODAL = "SHOW_CONTEST_ENDED_MODAL";
export const HIDE_CONTEST_ENDED_MODAL = "HIDE_CONTEST_ENDED_MODAL";

export const SET_CODE = "SET_CODE";
