export const SET_THEME = "SET_THEME"
export const SET_LANGUAGE = "SET_LANGUAGE"
export const SET_FONT_SIZE = "SET_FONT_SIZE"

export const SET_INPUT = "SET_INPUT"
export const SET_OUTPUT = "SET_OUTPUT"

export const SET_LOADING = "SET_LOADING"
export const RESET_LOADING = "RESET_LOADING"

export const SET_COMPILE_ON = "SET_COMPILE_ON"
export const SET_COMPILE_OFF = "SET_COMPILE_OFF"

export const CREATE_ROOM = "CREATE_ROOM"
export const LEAVE_ROOM = "LEAVE_ROOM"

export const SHOW_GRAPH = "SHOW_GRAPH"
export const HIDE_GRAPH = "HIDE_GRAPH"

export const NOTIFY_OUTPUT_SUCCESS = "NOTIFY_OUTPUT_SUCCESS";
export const NOTIFY_OUTPUT_ERROR = "NOTIFY_OUTPUT_ERROR";

export const SET_SOME_ONE_SEND_IO= "SET_SOME_ONE_SEND_IO"
export const RESET_SOME_ONE_SEND_IO= "RESET_SOME_ONE_SEND_IO"

export const BLOGPOSTED = "BLOGPOSTED"
