import React from "react";
import { InputLabel, MenuItem, FormControl, Select } from "@material-ui/core";

import classes from "./update.module.css";

const CountrySelect = (props) => {
  return (
    <FormControl className={classes.Country} style={{ marginTop: "20px" }}>
      <InputLabel>Country</InputLabel>
      <Select
        onChange={(e) => props.changeHandler(e.target.value)}
        value={props.country}
      >
        {countries.map((country, idx) => (
          <MenuItem key={idx} value={country.label}>
            {country.label}
          </MenuItem>
        ))}
      </Select>
    </FormControl>
  );
};

export default CountrySelect;

const countries = [
  { id: 2, label: "United Arab Emirates" },
  { id: 3, label: "Afghanistan" },
  { id: 4, label: "Antigua and Barbuda" },
  { id: 6, label: "Albania" },
  { id: 7, label: "Armenia" },
  { id: 8, label: "Angola" },
  { id: 9, label: "Antarctica" },
  { id: 10, label: "Argentina" },
  { id: 11, label: "American Samoa" },
  { id: 12, label: "Austria" },
  { id: 13, label: "Australia" },
  { id: 15, label: "Alland Islands" },
  { id: 16, label: "Azerbaijan" },
  { id: 18, label: "Barbados" },
  { id: 19, label: "Bangladesh" },
  { id: 20, label: "Belgium" },
  { id: 22, label: "Bulgaria" },
  { id: 23, label: "Bahrain" },
  { id: 24, label: "Burundi" },
  { id: 27, label: "Bermuda" },
  { id: 29, label: "Bolivia" },
  { id: 30, label: "Brazil" },
  { id: 31, label: "Bahamas" },
  { id: 32, label: "Bhutan" },
  { id: 34, label: "Botswana" },
  { id: 35, label: "Belarus" },
  { id: 37, label: "Canada" },
  { id: 40, label: "Central African Republic" },
  { id: 41, label: "Congo, Republic of the" },
  { id: 42, label: "Switzerland" },
  { id: 44, label: "Cook Islands" },
  { id: 45, label: "Chile" },
  { id: 46, label: "Cameroon" },
  { id: 47, label: "China" },
  { id: 48, label: "Colombia" },
  { id: 49, label: "Costa Rica" },
  { id: 50, label: "Cuba" },
  { id: 51, label: "Cape Verde" },
  { id: 53, label: "Christmas Island" },
  { id: 54, label: "Cyprus" },
  { id: 55, label: "Czech Republic" },
  { id: 56, label: "Germany" },
  { id: 57, label: "Djibouti" },
  { id: 58, label: "Denmark" },
  { id: 59, label: "Dominica" },
  { id: 60, label: "Dominican Republic" },
  { id: 61, label: "Algeria" },
  { id: 62, label: "Ecuador" },
  { id: 63, label: "Estonia" },
  { id: 64, label: "Egypt" },
  { id: 65, label: "Western Sahara" },
  { id: 66, label: "Eritrea" },
  { id: 67, label: "Spain" },
  { id: 68, label: "Ethiopia" },
  { id: 69, label: "Finland" },
  { id: 70, label: "Fiji" },
  { id: 74, label: "France" },
  { id: 76, label: "United Kingdom" },
  { id: 78, label: "Georgia" },
  { id: 81, label: "Ghana" },
  { id: 82, label: "Gibraltar" },
  { id: 84, label: "Gambia" },
  { id: 85, label: "Guinea" },
  { id: 87, label: "Equatorial Guinea" },
  { id: 88, label: "Greece" },
  { id: 94, label: "Hong Kong" },
  { id: 99, label: "Hungary" },
  { id: 100, label: "Indonesia" },
  { id: 101, label: "Ireland" },
  { id: 104, label: "India" },
  { id: 106, label: "Iraq" },
  { id: 107, label: "Iran" },
  { id: 108, label: "Iceland" },
  { id: 109, label: "Italy" },
  { id: 110, label: "Jersey" },
  { id: 111, label: "Jamaica" },
  { id: 112, label: "Jordan" },
  { id: 113, label: "Japan" },
  { id: 114, label: "Kenya" },
  { id: 115, label: "Kyrgyzstan" },
  { id: 116, label: "Cambodia" },
  { id: 120, label: "Korea, Democratic People's Republic of" },
  { id: 121, label: "Korea, Republic of" },
  { id: 122, label: "Kuwait" },
  { id: 124, label: "Kazakhstan" },
  { id: 125, label: "Lao People's Democratic Republic" },
  { id: 126, label: "Lebanon" },
  { id: 127, label: "Saint Lucia" },
  { id: 129, label: "Sri Lanka" },
  { id: 130, label: "Liberia" },
  { id: 131, label: "Lesotho" },
  { id: 132, label: "Lithuania" },
  { id: 133, label: "Luxembourg" },
  { id: 134, label: "Latvia" },
  { id: 135, label: "Libya" },
  { id: 136, label: "Morocco" },
  { id: 137, label: "Monaco" },
  { id: 138, label: "Moldova, Republic of" },
  { id: 141, label: "Madagascar" },
  { id: 143, label: "Macedonia" },
  { id: 144, label: "Mali" },
  { id: 145, label: "Myanmar" },
  { id: 146, label: "Mongolia" },
  { id: 147, label: "Macao" },
  { id: 150, label: "Mauritania" },
  { id: 152, label: "Malta" },
  { id: 153, label: "Mauritius" },
  { id: 154, label: "Maldives" },
  { id: 155, label: "Malawi" },
  { id: 156, label: "Mexico" },
  { id: 157, label: "Malaysia" },
  { id: 158, label: "Mozambique" },
  { id: 159, label: "Namibia" },
  { id: 160, label: "New Caledonia" },
  { id: 161, label: "Niger" },
  { id: 163, label: "Nigeria" },
  { id: 165, label: "Netherlands" },
  { id: 166, label: "Norway" },
  { id: 167, label: "Nepal" },
  { id: 170, label: "New Zealand" },
  { id: 171, label: "Oman" },
  { id: 172, label: "Panama" },
  { id: 173, label: "Peru" },
  { id: 175, label: "Papua New Guinea" },
  { id: 176, label: "Philippines" },
  { id: 177, label: "Pakistan" },
  { id: 178, label: "Poland" },
  { id: 179, label: "Saint Pierre and Miquelon" },
  { id: 182, label: "Palestine" },
  { id: 183, label: "Portugal" },
  { id: 185, label: "Paraguay" },
  { id: 186, label: "Qatar" },
  { id: 187, label: "Reunion" },
  { id: 188, label: "Romania" },
  { id: 189, label: "Serbia" },
  { id: 190, label: "Russian Federation" },
  { id: 191, label: "Rwanda" },
  { id: 192, label: "Saudi Arabia" },
  { id: 193, label: "Solomon Islands" },
  { id: 195, label: "Sudan" },
  { id: 196, label: "Sweden" },
  { id: 197, label: "Singapore" },
  { id: 199, label: "Slovenia" },
  { id: 201, label: "Slovakia" },
  { id: 203, label: "San Marino" },
  { id: 204, label: "Senegal" },
  { id: 205, label: "Somalia" },
  { id: 207, label: "South Sudan" },
  { id: 209, label: "El Salvador" },
  { id: 211, label: "Syrian Arab Republic" },
  { id: 213, label: "Turks and Caicos Islands" },
  { id: 217, label: "Thailand" },
  { id: 218, label: "Tajikistan" },
  { id: 219, label: "Tokelau" },
  { id: 220, label: "Timor-Leste" },
  { id: 221, label: "Turkmenistan" },
  { id: 222, label: "Tunisia" },
  { id: 224, label: "Turkey" },
  { id: 228, label: "United Republic of Tanzania" },
  { id: 229, label: "Ukraine" },
  { id: 231, label: "United States" },
  { id: 232, label: "Uruguay" },
  { id: 233, label: "Uzbekistan" },
  { id: 234, label: "Holy See (Vatican City State)" },
  { id: 236, label: "Venezuela" },
  { id: 239, label: "Vietnam" },
  { id: 242, label: "Samoa" },
  { id: 243, label: "Kosovo" },
  { id: 244, label: "Yemen" },
  { id: 246, label: "South Africa" },
  {id:247,label:'other'},
];
