import React from "react";
import Grid from "@material-ui/core/Grid";
import InputLabel from "@material-ui/core/InputLabel";
import MenuItem from "@material-ui/core/MenuItem";
import { makeStyles } from "@material-ui/core/styles";
import FormControl from "@material-ui/core/FormControl";
import Select from "@material-ui/core/Select";

const CountrySelect = (props) => {
  return (
    <FormControl style={{ width: props.width, marginTop: "20px" }}>
      <InputLabel>Country</InputLabel>
      <Select
        onChange={(e) => props.changeHandler(e.target.value)}
        value={props.country}
      >
        {countries.map((country, idx) => (
          <MenuItem value={country.id}>{country.label}</MenuItem>
        ))}
      </Select>
    </FormControl>
  );
};

export default CountrySelect;

const countries = [
  { id: 1, label: "Andorra" },
  { id: 2, label: "United Arab Emirates" },
  { id: 3, label: "Afghanistan" },
  { id: 4, label: "Antigua and Barbuda" },
  { id: 5, label: "Anguilla" },
  { id: 6, label: "Albania" },
  { id: 7, label: "Armenia" },
  { id: 8, label: "Angola" },
  { id: 9, label: "Antarctica" },
  { id: 10, label: "Argentina" },
  { id: 11, label: "American Samoa" },
  { id: 12, label: "Austria" },
  { id: 13, label: "Australia" },
  { id: 14, label: "Aruba" },
  { id: 15, label: "Alland Islands" },
  { id: 16, label: "Azerbaijan" },
  { id: 17, label: "Bosnia and Herzegovina" },
  { id: 18, label: "Barbados" },
  { id: 19, label: "Bangladesh" },
  { id: 20, label: "Belgium" },
  { id: 21, label: "Burkina Faso" },
  { id: 22, label: "Bulgaria" },
  { id: 23, label: "Bahrain" },
  { id: 24, label: "Burundi" },
  { id: 25, label: "Benin" },
  { id: 26, label: "Saint Barthelemy" },
  { id: 27, label: "Bermuda" },
  { id: 28, label: "Brunei Darussalam" },
  { id: 29, label: "Bolivia" },
  { id: 30, label: "Brazil" },
  { id: 31, label: "Bahamas" },
  { id: 32, label: "Bhutan" },
  { id: 33, label: "Bouvet Island" },
  { id: 34, label: "Botswana" },
  { id: 35, label: "Belarus" },
  { id: 36, label: "Belize" },
  { id: 37, label: "Canada" },
  { id: 38, label: "Cocos (Keeling) Islands" },
  { id: 39, label: "Congo, Democratic Republic of the" },
  { id: 40, label: "Central African Republic" },
  { id: 41, label: "Congo, Republic of the" },
  { id: 42, label: "Switzerland" },
  { id: 43, label: "Cote d'Ivoire" },
  { id: 44, label: "Cook Islands" },
  { id: 45, label: "Chile" },
  { id: 46, label: "Cameroon" },
  { id: 47, label: "China" },
  { id: 48, label: "Colombia" },
  { id: 49, label: "Costa Rica" },
  { id: 50, label: "Cuba" },
  { id: 51, label: "Cape Verde" },
  { id: 52, label: "Curacao" },
  { id: 53, label: "Christmas Island" },
  { id: 54, label: "Cyprus" },
  { id: 55, label: "Czech Republic" },
  { id: 56, label: "Germany" },
  { id: 57, label: "Djibouti" },
  { id: 58, label: "Denmark" },
  { id: 59, label: "Dominica" },
  { id: 60, label: "Dominican Republic" },
  { id: 61, label: "Algeria" },
  { id: 62, label: "Ecuador" },
  { id: 63, label: "Estonia" },
  { id: 64, label: "Egypt" },
  { id: 65, label: "Western Sahara" },
  { id: 66, label: "Eritrea" },
  { id: 67, label: "Spain" },
  { id: 68, label: "Ethiopia" },
  { id: 69, label: "Finland" },
  { id: 70, label: "Fiji" },
  { id: 71, label: "Falkland Islands (Malvinas)" },
  { id: 72, label: "Micronesia, Federated States of" },
  { id: 73, label: "Faroe Islands" },
  { id: 74, label: "France" },
  { id: 75, label: "Gabon" },
  { id: 76, label: "United Kingdom" },
  { id: 77, label: "Grenada" },
  { id: 78, label: "Georgia" },
  { id: 79, label: "French Guiana" },
  { id: 80, label: "Guernsey" },
  { id: 81, label: "Ghana" },
  { id: 82, label: "Gibraltar" },
  { id: 83, label: "Greenland" },
  { id: 84, label: "Gambia" },
  { id: 85, label: "Guinea" },
  { id: 86, label: "Guadeloupe" },
  { id: 87, label: "Equatorial Guinea" },
  { id: 88, label: "Greece" },
  { id: 89, label: "South Georgia and the South Sandwich Islands" },
  { id: 90, label: "Guatemala" },
  { id: 91, label: "Guam" },
  { id: 92, label: "Guinea-Bissau" },
  { id: 93, label: "Guyana" },
  { id: 94, label: "Hong Kong" },
  { id: 95, label: "Heard Island and McDonald Islands" },
  { id: 96, label: "Honduras" },
  { id: 97, label: "Croatia" },
  { id: 98, label: "Haiti" },
  { id: 99, label: "Hungary" },
  { id: 100, label: "Indonesia" },
  { id: 101, label: "Ireland" },
  { id: 102, label: "Israel" },
  { id: 103, label: "Isle of Man" },
  { id: 104, label: "India" },
  { id: 105, label: "British Indian Ocean Territory" },
  { id: 106, label: "Iraq" },
  { id: 107, label: "Iran, Islamic Republic of" },
  { id: 108, label: "Iceland" },
  { id: 109, label: "Italy" },
  { id: 110, label: "Jersey" },
  { id: 111, label: "Jamaica" },
  { id: 112, label: "Jordan" },
  { id: 113, label: "Japan" },
  { id: 114, label: "Kenya" },
  { id: 115, label: "Kyrgyzstan" },
  { id: 116, label: "Cambodia" },
  { id: 117, label: "Kiribati" },
  { id: 118, label: "Comoros" },
  { id: 119, label: "Saint Kitts and Nevis" },
  { id: 120, label: "Korea, Democratic People's Republic of" },
  { id: 121, label: "Korea, Republic of" },
  { id: 122, label: "Kuwait" },
  { id: 123, label: "Cayman Islands" },
  { id: 124, label: "Kazakhstan" },
  { id: 125, label: "Lao People's Democratic Republic" },
  { id: 126, label: "Lebanon" },
  { id: 127, label: "Saint Lucia" },
  { id: 128, label: "Liechtenstein" },
  { id: 129, label: "Sri Lanka" },
  { id: 130, label: "Liberia" },
  { id: 131, label: "Lesotho" },
  { id: 132, label: "Lithuania" },
  { id: 133, label: "Luxembourg" },
  { id: 134, label: "Latvia" },
  { id: 135, label: "Libya" },
  { id: 136, label: "Morocco" },
  { id: 137, label: "Monaco" },
  { id: 138, label: "Moldova, Republic of" },
  { id: 139, label: "Montenegro" },
  { id: 140, label: "Saint Martin (French part)" },
  { id: 141, label: "Madagascar" },
  { id: 142, label: "Marshall Islands" },
  { id: 143, label: "Macedonia, the Former Yugoslav Republic of" },
  { id: 144, label: "Mali" },
  { id: 145, label: "Myanmar" },
  { id: 146, label: "Mongolia" },
  { id: 147, label: "Macao" },
  { id: 148, label: "Northern Mariana Islands" },
  { id: 149, label: "Martinique" },
  { id: 150, label: "Mauritania" },
  { id: 151, label: "Montserrat" },
  { id: 152, label: "Malta" },
  { id: 153, label: "Mauritius" },
  { id: 154, label: "Maldives" },
  { id: 155, label: "Malawi" },
  { id: 156, label: "Mexico" },
  { id: 157, label: "Malaysia" },
  { id: 158, label: "Mozambique" },
  { id: 159, label: "Namibia" },
  { id: 160, label: "New Caledonia" },
  { id: 161, label: "Niger" },
  { id: 162, label: "Norfolk Island" },
  { id: 163, label: "Nigeria" },
  { id: 164, label: "Nicaragua" },
  { id: 165, label: "Netherlands" },
  { id: 166, label: "Norway" },
  { id: 167, label: "Nepal" },
  { id: 168, label: "Nauru" },
  { id: 169, label: "Niue" },
  { id: 170, label: "New Zealand" },
  { id: 171, label: "Oman" },
  { id: 172, label: "Panama" },
  { id: 173, label: "Peru" },
  { id: 174, label: "French Polynesia" },
  { id: 175, label: "Papua New Guinea" },
  { id: 176, label: "Philippines" },
  { id: 177, label: "Pakistan" },
  { id: 178, label: "Poland" },
  { id: 179, label: "Saint Pierre and Miquelon" },
  { id: 180, label: "Pitcairn" },
  { id: 181, label: "Puerto Rico" },
  { id: 182, label: "Palestine, State of" },
  { id: 183, label: "Portugal" },
  { id: 184, label: "Palau" },
  { id: 185, label: "Paraguay" },
  { id: 186, label: "Qatar" },
  { id: 187, label: "Reunion" },
  { id: 188, label: "Romania" },
  { id: 189, label: "Serbia" },
  { id: 190, label: "Russian Federation" },
  { id: 191, label: "Rwanda" },
  { id: 192, label: "Saudi Arabia" },
  { id: 193, label: "Solomon Islands" },
  { id: 194, label: "Seychelles" },
  { id: 195, label: "Sudan" },
  { id: 196, label: "Sweden" },
  { id: 197, label: "Singapore" },
  { id: 198, label: "Saint Helena" },
  { id: 199, label: "Slovenia" },
  { id: 200, label: "Svalbard and Jan Mayen" },
  { id: 201, label: "Slovakia" },
  { id: 202, label: "Sierra Leone" },
  { id: 203, label: "San Marino" },
  { id: 204, label: "Senegal" },
  { id: 205, label: "Somalia" },
  { id: 206, label: "Suriname" },
  { id: 207, label: "South Sudan" },
  { id: 208, label: "Sao Tome and Principe" },
  { id: 209, label: "El Salvador" },
  { id: 210, label: "Sint Maarten (Dutch part)" },
  { id: 211, label: "Syrian Arab Republic" },
  { id: 212, label: "Swaziland" },
  { id: 213, label: "Turks and Caicos Islands" },
  { id: 214, label: "Chad" },
  { id: 215, label: "French Southern Territories" },
  { id: 216, label: "Togo" },
  { id: 217, label: "Thailand" },
  { id: 218, label: "Tajikistan" },
  { id: 219, label: "Tokelau" },
  { id: 220, label: "Timor-Leste" },
  { id: 221, label: "Turkmenistan" },
  { id: 222, label: "Tunisia" },
  { id: 223, label: "Tonga" },
  { id: 224, label: "Turkey" },
  { id: 225, label: "Trinidad and Tobago" },
  { id: 226, label: "Tuvalu" },
  { id: 227, label: "Taiwan, Province of China" },
  { id: 228, label: "United Republic of Tanzania" },
  { id: 229, label: "Ukraine" },
  { id: 230, label: "Uganda" },
  { id: 231, label: "United States" },
  { id: 232, label: "Uruguay" },
  { id: 233, label: "Uzbekistan" },
  { id: 234, label: "Holy See (Vatican City State)" },
  { id: 235, label: "Saint Vincent and the Grenadines" },
  { id: 236, label: "Venezuela" },
  { id: 237, label: "British Virgin Islands" },
  { id: 238, label: "US Virgin Islands" },
  { id: 239, label: "Vietnam" },
  { id: 240, label: "Vanuatu" },
  { id: 241, label: "Wallis and Futuna" },
  { id: 242, label: "Samoa" },
  { id: 243, label: "Kosovo" },
  { id: 244, label: "Yemen" },
  { id: 245, label: "Mayotte" },
  { id: 246, label: "South Africa" },
  { id: 247, label: "Zambia" },
  { id: 248, label: "Zimbabwe" },
];
